language: node_js
node_js:
  - "10.16.0"
cache:
  directories:
    "node_modules"

script:
  - npm test -- --coverage --watchAll=false
  - npm run build

after_script:
  - COVERALLS_REPO_TOKEN=$repo_token npm run coveralls

after_success:
  - npm run coveralls
